// Applies pending SQL migrations from ./drizzle (generated by `npm run
// db:generate`) to the database at DATABASE_URL. Run this once per schema
// change, in every environment (including production, after a deploy that
// changed schema.ts).

import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error("DATABASE_URL is not set.");
  }
  const client = postgres(url, { max: 1 });
  const db = drizzle(client);
  console.log("Running migrations from ./drizzle ...");
  await migrate(db, { migrationsFolder: "./drizzle" });
  console.log("Migrations applied.");
  await client.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
